# prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # 1. Prometheus self‐scrape
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s

  # 2. Node.js application metrics
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['nodejs-app:3000']  # within Docker network, use service name
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: 10s
    scrape_timeout: 5s
