# Prometheus configuration for monitoring EC2 application
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Monitor Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Monitor Node.js application on EC2
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['54.169.170.65:3000'] # Replace with your EC2 public IP
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Monitor Node Exporter on EC2 (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['54.169.170.65:9100'] # Replace with your EC2 public IP
    scrape_interval: 15s
    scrape_timeout: 10s

  # Optional: Monitor local application during development
  - job_name: 'nodejs-app-local'
    static_configs:
      - targets: ['host.docker.internal:3000'] # For local testing
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s